apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: external
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "external",
      "type": "macvlan",
      "master": "ospbr",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.0.0/24",
        "range_start": "10.0.0.30",
        "range_end": "10.0.0.70"
      }
    }

